<?php
// This file generated by Propel 1.6.8 convert-conf target
// from XML runtime conf file /Users/Bilou/GitHub/Pollina/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'pollina' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=127.0.0.1;dbname=pollina',
        'user' => 'root',
        'password' => 'root',
      ),
    ),
    'default' => 'pollina',
  ),
  'generator_version' => '1.6.8',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-pollina-conf.php');
return $conf;